# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            cliff538
tagline:          'Never Stop Learning'
description:      'My journey learning Swift and a lot of other stuff...'
url:              http://cliff538.github.io

author:
  name:           'cliff538'
  url:            https://twitter.com/cliff538

paginate:         5

#Custom vars
version:          2.0.0

github:
 repo:           https://github.com/cliff538


pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
